name: Arduino CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Instalar core AVR
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      - name: Compilar sketch
        run: |
          arduino-cli compile --fqbn arduino:avr:uno Codigo/tu_sketch.ino
